# settings.py
# Game configuration and settings

DEFAULT_WARRIOR_HEALTH = 120
DEFAULT_MAGE_HEALTH = 80
HEALTH_POTION_AMOUNT = 30
HEAVY_STRIKE_MIN = 5
HEAVY_STRIKE_MAX = 15
FIREBALL_MIN = 10
FIREBALL_MAX = 20
POISON_DAMAGE = 5
POISON_DURATION = 3
HEAL_AMOUNT = 25

WIDTH = 800
HEIGHT = 600